### ISSUE TITLE
Is There a Version 8.1.3 of This Module?

### ISSUE THREAD

**Issue by Andy9999** [DNNCommunity/DNN.Vendors#30]
When checking (DNN 9.9.0) in "Persona Bar" -> "Settings" -> "Extensions", it says there is a newer version 8.1.3. Am on 8.1.0 of the module and I cannot find 8.1.3.

Does that module version exist? And where is "Extensions" getting this info from? Is it maybe for DNN v10?

**Comment by jncraig** [comment]
The upgrade notice thing is not working correctly.  I think I saw a note from Mitch Sellers yesterday that said they hope to have it working "in a few days."  So ... don't pay attention to it ... not quite yet.

**Comment by Andy9999** [comment]
OK. Then I will wait for a few days and try again. :)
