### ISSUE TITLE
Remove Telerik dependencies

### ISSUE THREAD

**Issue by thenotandy** [DNNCommunity/DNN.Vendors#31]
Error: Vendors is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Unable to create type 'dnn:DnnComboBox'. 

DotNetNuke.Services.Exceptions.ModuleLoadException: Could not load file or assembly 'DotNetNuke.Web.Deprecated' or one of its dependencies.

**Comment by WillStrohl** [comment]
Thanks for logging this error message.  Can you please provide more details to help us understand how you got to the error message?  In general, we need you to follow the prescribed error reporting format.  Otherwise, it may be difficult (or impossible) for any developer to reproduce and fix the issue.  See below.  

```  
## Describe the bug
A clear and concise description of what the bug is.

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
A clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

## Additional context
Add any other context about the problem here.
```

**Comment by cklenk** [comment]
Found DnnComboBox, DnnGrid, DnnDatePicker controls in solution which depend on Telerik.

**Comment by WillStrohl** [comment]
Steps to Reproduce and the rest of the bug reporting format is required for nearly any open-source project issue.  :)

**Comment by cklenk** [comment]
@hismightiness will do! I think the gist of it is if you use this module on a dnn site with telerik removed it bombs out because it's using telerik for the controls. I can get your a more detailed write up later. Thank you.

**Comment by valadas** [comment]
Done in #32
