### ISSUE TITLE
Column wrapping

### ISSUE THREAD

**Issue by rstordeur** [DNNCommunity/DNN.Vendors#4]
Current in the BannerView, the columns do not have a setting to wrap.  Therefore if the number of banners exceed the width of the module setting, they overflow to the right.  I submitted this years ago but it never got acted on.  The wrap should be a fairly simple addition of a datagrid tied to a DB setting for each instance of the module.  The setting would read the number of columns for that instance of the module.

For example, at several charities that I support, they list their sponsors on a Sponsors page.  I had to change them to a text module that they had to manually edit instead of just add another banner with the proper category.  Their page has 3 columns wide and extend to another row.

**Comment by valadas** [comment]
The new release is now templatable which should solve this issue
