### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by JohnnyLoki** [DNNCommunity/DNN.Vendors#5]
when installing on DNN 8.0.0 or 8.0.1 you get a critical error

**Comment by DavidSimpli** [comment]
Perhaps this issue be related to the use of the incorrect zip file. 
The correct zip file is in the path:
..\DNN.Vendors-master\DNN.Vendors-master\DNN.Vendors-master\src\Dnn.Modules.Vendors\Install\DNNCE_Vendors_08.00.00_Install.zip

**Comment by valadas** [comment]
I am closing this issue due to a lack of details on the issue, if this is still a problem, please open a new issue.
