### ISSUE TITLE
Error on redirect

### ISSUE THREAD

**Issue by martingithubch** [DNNCommunity/DNN.Vendors#7]
Hi All,
after the upgrade to DNN 8.x I had to install the Vendors Module from github. I recognized today that the redirect doesn’t work. I’ve another error then on post before where the redir file wasn’t found. I got the errro: 

_Line 31: using DotNetNuke.Services.Vendors; 
"The type or namespace name 'Vendors' does not exist in the namespace 'DotNetNuke.Services' (are you missing an assembly reference?)”_

Any ideas how to solve this issue? I’ve already tried a reparation of the module, 
Thanks
Martin

**Comment by roman-yagodin** [comment]
@martingithubch, do you have this error with your skin or with *Banners* module? Note that current *Vendors* package doesn't contains a banner skinobject (see #1).

I have similar issue with a skin which use banner skin object. If it is your case also, find following `using` directive in `/Admin/Skins/Banner.ascx.cs` (if you have one remaining from previous DNN version):

```
using DotNetNuke.Services.Vendors;
```
And replace it with following 2 directives:
```
using Dnn.Modules.Vendors;
using Dnn.Modules.Vendors.Components;
```

Banners should start to display after that, but you should still have a redirect issue (see #6).

**Comment by valadas** [comment]
I am closing this issue because it duplicated #1 and #6, please follow up on those if needed.
